/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CardCamera: typeof import('./src/components/CardCamera.vue')['default']
    CardCameraSelected: typeof import('./src/components/CardCameraSelected.vue')['default']
    EditButton: typeof import('./src/components/EditButton.vue')['default']
    EditExpPanel: typeof import('./src/components/EditExpPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LanBar: typeof import('./src/components/lan-bar.vue')['default']
    NavBar: typeof import('./src/components/nav-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
